### ISSUE TITLE
Issue in page Flashing (x86_64)

### ISSUE THREAD

**Issue by Brettinthewoods** [Start9Labs/documentation#412]
I would like to report an issue in page https://docs.start9.com/master/user-manual/flashing/flashing-x86

### Problem
Incorrect instruction for verifying Checksum hash on Windows. "Get-FileHash" is a PowerShell command and does not work in cmd

###  Suggest a fix
Change copy for Windows to instruct user to open a PowerShell terminal instead of cmd

**Comment by gStart9** [comment]
This was fixed in this commit:

https://github.com/Start9Labs/documentation/commit/297725ae4e004cf6e1a5ace2dde848f3df61af4f
(Line 40)

I'm not sure why it's not showing up on https://docs.start9.com because I was pretty sure that was pushed up by now -- Any idea @kn0wmad?

**Comment by Brettinthewoods** [comment]
@gStart9 

Looks like you fixed it on the Raspberry Pi page. The error is still present on the x86_64 page.

**Comment by gStart9** [comment]
Ahhh, yes, thank you.  Will fix the raspi page.

**Comment by gStart9** [comment]
Should be fixed by https://github.com/Start9Labs/documentation/pull/413 Which is now awaiting review

**Comment by kn0wmad** [comment]
Approved, merge away @gStart9 

Thanks for the report @Brettinthewoods
